USE [master]

GO

CREATE SERVER AUDIT [AudiServidor]
TO FILE 
(	FILEPATH = N'C:\SQL\IConvocatoria\Audit'
	,MAXSIZE = 0 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)

GO


